#!/bin/sh
ROOT_DIR=../../..
LIBS=$ROOT_DIR/lib
ROOTBEER=$LIBS/rootbeer-1.x-SNAPSHOT.jar

# Set library jars
LIB_JARS="lib/tjungblut-math-1.0.jar"

# Ant
ant clean
ant jar-rb

# Pack libraries
#java -jar ../pack.jar -mainjar PiEstimator.jar -libjar $LIBS/tjungblut-math-1.0.jar -destjar PiEstimator-rb.jar

# Rootbeer
java -jar $ROOTBEER PiEstimator-rb.jar PiEstimator-rb-GPU.jar

# Combine Rootbeer-GPU (Kernel with other Sources)
ant jar-gpu-combine

# Include lib jars
for jar in $LIB_JARS
do
  jar uf PiEstimator.jar -C $ROOT_DIR $jar
done

#hama jar PiEstimator.jar